api/urls.py
from django.urls import path
from .views import RoomView, CreateRoomView, GetRoom, JoinRoom, UserInRoom, LeaveRoom, UpdateRoom

urlpatterns = [
    path('room', RoomView.as_view()),
    path('create-room', CreateRoomView.as_view()),
    path('get-room', GetRoom.as_view()),
    path('join-room', JoinRoom.as_view()),
    path('user-in-room', UserInRoom.as_view()),
    path('leave-room', LeaveRoom.as_view()),
    path('update-room', UpdateRoom.as_view())
]

frontend/urls.py
from django.urls import path
from .views import index, feedback_form

app_name = 'frontend'

urlpatterns = [
    path('', index, name=''),
    path('home', index),
    path('info', index),
    path('join', index),
    path('create', index),
    path('room/<str:roomCode>', index),
    path('feedback', feedback_form, name='form')
]

music_controller/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('frontend.urls')),
    path('spotify/', include('spotify.urls'))
]

frontend/models.py
from django.db import models


class Feedback(models.Model):
    customer_name = models.CharField(max_length=120)
    email = models.EmailField()
    details = models.TextField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.customer_name

frontend/forms.py
from django import forms

from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = []

frontend/views.py
from .forms import FeedbackForm
from django.shortcuts import render

# Create your views here.


def index(request, *args, **kwargs):
    return render(request, 'frontend/index.html')


def feedback_form(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request, 'frontend/thanks.html')
    else:
        form = FeedbackForm()
    return render(request, 'frontend/feedback_form.html', {'feedback_form': form})

frontend/templates/frontend/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link
            rel="stylesheet"
            type="text/css"
            href="../../static/css/form.css"
        />
    </head>
    <body>
        {% block body %} {% endblock %}
    </body>
</html>

frontend/templates/frontend/feedback_form.html
<script>
    function goBack(e) {
        e.preventDefault();
        console.log("hello");
        window.location = window.location.href.slice(0, -8);
    }
</script>
{% extends 'frontend/base.html' %} {% block title %}Feedback Form{% endblock %}
{% block body %}
<form action="{% url 'frontend:form' %}" method="POST">
    {% csrf_token %}
    <div class="background">
        <div class="container">
            <div class="screen">
                <div class="screen-header">
                    <div class="screen-header-left">
                        <div class="screen-header-button close"></div>
                        <div class="screen-header-button maximize"></div>
                        <div class="screen-header-button minimize"></div>
                    </div>
                    <div class="screen-header-right">
                        <div class="screen-header-ellipsis"></div>
                        <div class="screen-header-ellipsis"></div>
                        <div class="screen-header-ellipsis"></div>
                    </div>
                </div>
                <div class="screen-body">
                    <div class="screen-body-item left">
                        <div class="app-title">
                            <p>
                                GIVE FEEDBACK <br />
                                OR <br />
                                REQUEST FOR PASSWORD CHANGE
                            </p>
                        </div>
                    </div>
                    <div class="screen-body-item">
                        <div class="app-form">
                            <div class="app-form-group">
                                <input
                                    class="app-form-control"
                                    placeholder="NAME"
                                    name="customer_name"
                                />
                            </div>
                            <div class="app-form-group">
                                <input
                                    class="app-form-control"
                                    placeholder="EMAIL"
                                    name="email"
                                />
                            </div>
                            <div class="app-form-group message">
                                <input
                                    class="app-form-control"
                                    placeholder="MESSAGE"
                                    name="details"
                                />
                            </div>
                            <div class="app-form-group buttons">
                                <input class="app-form-button" type="submit" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div>
                <button class="home-btn" onclick="goBack(arguments[0]);">
                    HOME
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

frontend/templates/frontend/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Music Controller</title>
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    />
    <link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}"
    />
  </head>
  <body>
    <div id="gradient">
      <div id="main">
        <div id="app"></div>
      </div>
    </div>
    <script src="{% static "frontend/main.js" %}"></script>
  </body>
</html>

frontend/templates/frontend/thanks.html
<script>
    setTimeout(function () {
        window.location = window.location.href.slice(0, -8);
    }, 3000);
</script>

{% extends 'frontend/base.html' %} {% block title %}Feedback Form{% endblock %}
{% block body %}
<center>
    <form action="{% url 'frontend:form' %}" method="POST">
        {% csrf_token %}
        <h1>Thanks for your response.</h1>
        <p>We will contact you ASAP</p>
        <p>This page will redirect to Home Page in 3 seconds</p>
    </form>
</center>
{% endblock %}